kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb
  namespace: kube-system
  annotations:
    volume.beta.kubernetes.io/storage-class: "kismatic"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi