---
  - include: _calico-network-policy.yaml play_name="Upgrade Network Policy Controller" upgrading=true
  - include: _kube-dns.yaml play_name="Upgrade Kubernetes DNS" upgrading=true
  - include: _kube-ingress.yaml play_name="Upgrade Kubernetes Ingress" upgrading=true
    when: configure_ingress|bool == true
  - include: _kube-dashboard.yaml play_name="Upgrade Kubernetes Dashboard" upgrading=true
  - include: _helm.yaml play_name="Upgrade Helm and Tiller" upgrading=true
    when: enable_helm|bool == true